#!/usr/bin/env python3
"""
init_project_structure.py - scaffold AI-friendly project structure.

MVP supports fullstack-web only. It creates directories and governance contract
files, not business code.
"""

import argparse
import shutil
from pathlib import Path

import yaml

from runtime_support import configure_console

configure_console()

DELIVERHQ_ROOT = Path(__file__).resolve().parent.parent
PROFILE_DIR = DELIVERHQ_ROOT / "structure-profiles"

README_TEXT = """# {name}\n\nPurpose: {purpose}\n\nAI / human review notes:\n- Keep this README small and current.\n- Document ownership, allowed dependencies, test location, and common mistakes.\n"""


def load_profile(profile_name: str):
    profile_path = PROFILE_DIR / (profile_name + ".yml")
    if not profile_path.exists():
        raise FileNotFoundError("unknown structure profile: %s" % profile_name)
    return profile_path, yaml.safe_load(profile_path.read_text(encoding="utf-8")) or {}


def ensure_dir(path: Path):
    path.mkdir(parents=True, exist_ok=True)


def write_if_missing(path: Path, content: str):
    if not path.exists():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")


def scaffold(project_root: Path, profile_name: str = "fullstack-web", force: bool = False):
    profile_path, profile = load_profile(profile_name)
    deliverhq_home = project_root / "DeliverHQ"

    for rel in profile.get("required_dirs", []):
        ensure_dir(project_root / rel)

    # Minimal module README files for AI/human navigation.
    readmes = {
        "apps/web/README.md": ("web", "Frontend UI application."),
        "apps/api/README.md": ("api", "Backend API application."),
        "apps/worker/README.md": ("worker", "Optional background worker service."),
        "packages/shared-types/README.md": ("shared-types", "Shared schemas and DTOs."),
        "infra/README.md": ("infra", "Deployment and infrastructure files."),
        "docs/README.md": ("docs", "Human-facing engineering documentation."),
    }
    for rel, (name, purpose) in readmes.items():
        write_if_missing(project_root / rel, README_TEXT.format(name=name, purpose=purpose))

    write_if_missing(project_root / ".env.example", "# Copy to .env locally. Never commit real secrets.\n")

    target_profile = deliverhq_home / "STRUCTURE-PROFILE.yml"
    if force or not target_profile.exists():
        target_profile.parent.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(profile_path, target_profile)

    repo_map = deliverhq_home / "REPO_MAP.md"
    write_if_missing(repo_map, repo_map_content(profile_name))

    commands = deliverhq_home / "COMMANDS.yml"
    write_if_missing(commands, commands_content())

    attention = deliverhq_home / "attention.md"
    write_if_missing(attention, attention_content(profile_name))

    for rel in ("notes", "inbox", "journal"):
        ensure_dir(deliverhq_home / rel)

    write_if_missing(deliverhq_home / "notes" / "_index.md", notes_index_content())
    write_if_missing(deliverhq_home / "inbox" / "README.md", inbox_readme_content())
    write_if_missing(deliverhq_home / "journal" / "README.md", journal_readme_content())

    return {
        "project_root": str(project_root),
        "profile": profile_name,
        "structure_profile": str(target_profile),
        "repo_map": str(repo_map),
        "commands": str(commands),
        "attention": str(attention),
    }


def repo_map_content(profile_name: str) -> str:
    return """# Repo Map\n\nProfile: `{profile}`\n\n## Apps\n\n| App | Path | Purpose |\n|---|---|---|\n| web | `apps/web` | Frontend UI |\n| api | `apps/api` | Backend API |\n| worker | `apps/worker` | Optional background jobs |\n\n## Shared Packages\n\n| Package | Path | Purpose |\n|---|---|---|\n| shared-types | `packages/shared-types` | Shared schemas and DTOs |\n| sdk | `packages/sdk` | Typed API client |\n| ui | `packages/ui` | Reusable UI components |\n\n## Review Boundaries\n\n- Frontend review: `apps/web/**`, `packages/ui/**`\n- Backend review: `apps/api/**`, `apps/worker/**`\n- Contract review: `packages/shared-types/**`, `packages/sdk/**`\n- Infra/security review: `infra/**`, `config/**`, `.env*`\n- DeliverHQ governance review: `DeliverHQ/**`\n\n## AI Rules\n\n- Read this file before exploring the repo.\n- Do not create new top-level directories without updating `DeliverHQ/STRUCTURE-PROFILE.yml`.\n- Put backend modules under `apps/api/src/modules/<feature>`.\n- Put frontend features under `apps/web/src/features/<feature>`.\n- Put shared contracts under `packages/shared-types`.\n""".format(profile=profile_name)


def commands_content() -> str:
    return """# COMMANDS.yml - generated by DeliverHQ init_project_structure.py\n\nbuild:\n  enabled: false\n  command: null\n  working_dir: \".\"\n  timeout: 300\n\ntest:\n  enabled: false\n  command: null\n  working_dir: \".\"\n  timeout: 600\n\nlint:\n  enabled: false\n  command: null\n  working_dir: \".\"\n  timeout: 300\n\ntypecheck:\n  enabled: false\n  command: null\n  working_dir: \".\"\n  timeout: 300\n"""


def attention_content(profile_name: str) -> str:
    return """# DeliverHQ Attention

Profile: `{profile}`

This is the lightweight, always-read project control file. Keep it short. Put
only constraints that should affect every DeliverHQ decision.

## Governance Lanes

| Lane | Use When | Default Evidence |
|---|---|---|
| quick | small single-surface change, no protected path, no production risk | direct change + relevant command output |
| standard | normal feature, bug fix, or refactor | lightweight CR + SpecGate/ReviewGate/QualityGate as needed |
| strict | auth, payment, security, data migration, production, protected paths | full fail-closed CR chain |
| legacy | existing code must be scanned before requirements are trusted | legacy scan + human confirmation |

Default lane: `standard`

## Read First

- `DeliverHQ/REPO_MAP.md`
- `DeliverHQ/COMMANDS.yml`
- Current CR under `DeliverHQ/change-requests/`, when one exists

## Risk Triggers

Escalate to `strict` when the change touches:

- authentication, authorization, payment, billing, security, privacy
- data migrations, irreversible writes, production configuration
- protected paths declared in `DeliverHQ/dir-graph.yaml`
- behavior where a false pass would harm users or operators

## Quick Knowledge Sinks

- Put confirmed reusable lessons in `DeliverHQ/notes/`.
- Put untriaged ideas or possible rules in `DeliverHQ/inbox/`.
- Put day-level handoff notes in `DeliverHQ/journal/`.
- Promote only durable rules or architecture decisions into `DeliverHQ/docs/`.
""".format(profile=profile_name)


def notes_index_content() -> str:
    return """# DeliverHQ Notes Index

One line per confirmed reusable lesson.

| Date | Area | Summary | File |
|---|---|---|---|
"""


def inbox_readme_content() -> str:
    return """# DeliverHQ Inbox

Capture untriaged ideas, possible rules, and follow-up questions here. Triage
items into `notes/`, `docs/`, or a CR when they become durable.
"""


def journal_readme_content() -> str:
    return """# DeliverHQ Journal

Use this for day-level progress notes and handoff summaries. Keep formal gate
evidence in the relevant CR directory.
"""


def main():
    parser = argparse.ArgumentParser(description="Scaffold AI-friendly project structure")
    parser.add_argument("project_root", nargs="?", default=".")
    parser.add_argument("--profile", default="fullstack-web")
    parser.add_argument("--force", action="store_true")
    args = parser.parse_args()

    result = scaffold(Path(args.project_root).resolve(), args.profile, args.force)
    print("✅ Project structure initialized")
    for key, value in result.items():
        print("%s: %s" % (key, value))


if __name__ == "__main__":
    main()
