#!/usr/bin/env python3
"""Derive agent-facing artifacts from DeliverHQ PRD.md.

PRD.md remains the human-owned product intent source. This script only writes
derived artifacts under docs/agent/ so agents can consume a compact, hash-bound
contract without reinterpreting the full PRD every time.
"""

import argparse
import hashlib
import json
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

import yaml

SCRIPT_DIR = Path(__file__).resolve().parent
if str(SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPT_DIR))

import prd_validate


GENERATED_HEADER = "<!-- GENERATED BY DeliverHQ prd_sync.py. DO NOT EDIT DIRECTLY. -->"


def sha256_text(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def is_template_section(section: str) -> bool:
    return "示例锚点" in section or "(同上结构)" in section


def extract_req_id(section: str) -> str:
    match = re.search(r"\*\*REQ ID\*\*:\s*(REQ-[A-Z0-9][A-Z0-9-]*)", section)
    return match.group(1) if match else ""


def extract_ids(prefix: str, section: str) -> list:
    pattern = rf"\b{prefix}-[A-Z0-9][A-Z0-9-]*\b"
    return sorted(set(re.findall(pattern, section)))


def extract_feature_title(section: str) -> str:
    first = section.splitlines()[0] if section.splitlines() else ""
    match = re.match(r"^##\s+\[[^\]]+\]\s*(.*?)\s*$", first)
    return match.group(1).strip() if match else ""


def extract_bullet_field(section: str, label: str) -> str:
    match = re.search(rf"^\s*-\s+\*\*{re.escape(label)}\*\*:\s*(.*?)\s*$", section, re.M)
    return match.group(1).strip() if match else ""


def extract_named_block(section: str, label: str) -> str:
    match = re.search(rf"^\*\*{re.escape(label)}\*\*.*$([\s\S]*?)(?=^\*\*[^*]+\*\*|^##\s|\Z)", section, re.M)
    return match.group(1).strip() if match else ""


def extract_acceptance_criteria(section: str) -> list:
    block = extract_named_block(section, "验收条件索引")
    criteria = []
    for line in block.splitlines():
        match = re.match(r"^\s*-\s+(AC-[A-Z0-9][A-Z0-9-]*):\s*(.+?)\s*$", line)
        if match:
            criteria.append({"id": match.group(1), "text": match.group(2)})
    return criteria


def extract_task_rows(section: str) -> list:
    block = extract_named_block(section, "研发交付映射")
    rows = []
    for line in block.splitlines():
        if not line.strip().startswith("|") or "---" in line:
            continue
        cells = [cell.strip() for cell in line.strip().strip("|").split("|")]
        if len(cells) < 5 or cells[0] in {"任务 ID", "Task ID"}:
            continue
        if cells[0].startswith("{{") or cells[0] in {"DEV-XXX", "QA-XXX"}:
            continue
        rows.append({
            "task_id": cells[0],
            "role": cells[1],
            "responsibility": cells[2],
            "covers": cells[3],
            "forbidden": cells[4],
        })
    return rows


def collect_features(prd_text: str) -> list:
    features = []
    for anchor, section in prd_validate._features(prd_text):
        if prd_validate.is_template_feature(anchor, section) or is_template_section(section):
            continue
        req_id = extract_req_id(section)
        features.append({
            "anchor": anchor,
            "title": extract_feature_title(section),
            "req_id": req_id,
            "priority": extract_bullet_field(section, "优先级") or extract_bullet_field(section, "浼樺厛绾?"),
            "owner": extract_bullet_field(section, "负责人") or extract_bullet_field(section, "璐熻矗浜?"),
            "target_platform": extract_bullet_field(section, "目标平台") or extract_bullet_field(section, "鐩爣骞冲彴"),
            "ac_ids": extract_ids("AC", section),
            "dev_ids": extract_ids("DEV", section),
            "qa_ids": extract_ids("QA", section),
            "invariant_ids": extract_ids("INV", section),
            "acceptance_criteria": extract_acceptance_criteria(section),
            "invariants_text": extract_named_block(section, "业务不变式"),
            "state_actions": extract_named_block(section, "状态与动作"),
            "task_rows": extract_task_rows(section),
            "hash": sha256_text(section),
        })
    return features


def build_manifest(prd_path: Path, prd_text: str, meta: dict, features: list) -> dict:
    now = datetime.now(timezone.utc).replace(microsecond=0).isoformat()
    return {
        "schema": "deliverhq-prd-manifest",
        "schema_version": 1,
        "generated_at": now,
        "source": {
            "path": str(prd_path),
            "prd_id": meta.get("prd_id", ""),
            "status": meta.get("status", ""),
            "schema_version": meta.get("schema_version", ""),
            "hash": sha256_text(prd_text),
        },
        "features": features,
    }


def build_task_map(manifest: dict) -> dict:
    tasks = []
    for feature in manifest["features"]:
        base = {
            "prd_anchor": feature["anchor"],
            "req_id": feature["req_id"],
            "ac_ids": feature["ac_ids"],
            "source_hash": feature["hash"],
        }
        rows = feature["task_rows"]
        for row in rows:
            tasks.append({**base, **row})
    return {
        "schema": "deliverhq-task-map",
        "schema_version": 1,
        "generated_at": manifest["generated_at"],
        "source_hash": manifest["source"]["hash"],
        "tasks": tasks,
    }


def build_acceptance_spec(manifest: dict) -> str:
    lines = [
        GENERATED_HEADER,
        "# Agent Acceptance Spec",
        "",
        "This file is derived from `docs/PRD.md`. Product intent must be changed in the PRD, then regenerated.",
        "",
        "```yaml",
        yaml.safe_dump({
            "schema": "deliverhq-agent-acceptance-spec",
            "schema_version": 1,
            "generated_at": manifest["generated_at"],
            "prd_id": manifest["source"].get("prd_id", ""),
            "prd_hash": manifest["source"]["hash"],
            "business_logic_authority": "backend",
            "client_role": "pure_ui_and_result_rendering",
        }, allow_unicode=True, sort_keys=False).strip(),
        "```",
        "",
        "## Traceability",
        "",
        "| PRD Anchor | REQ ID | AC IDs | Invariants | Source Hash |",
        "|---|---|---|---|---|",
    ]
    for feature in manifest["features"]:
        lines.append(
            "| {anchor} | {req_id} | {ac_ids} | {invariants} | {hash} |".format(
                anchor=feature["anchor"],
                req_id=feature["req_id"],
                ac_ids=", ".join(feature["ac_ids"]) or "-",
                invariants=", ".join(feature["invariant_ids"]) or "-",
                hash=feature["hash"],
            )
        )
        lines.extend(["", f"### {feature['anchor']} {feature['title']}", ""])
        lines.extend(["#### Acceptance Criteria", ""])
        if feature["acceptance_criteria"]:
            lines.extend(f"- **{item['id']}**: {item['text']}" for item in feature["acceptance_criteria"])
        else:
            lines.append("- No acceptance criteria provided")
        lines.extend(["", "#### Business Invariants", "", feature["invariants_text"] or "- None", ""])
        lines.extend(["#### State and Actions", "", feature["state_actions"] or "- None", ""])
    lines.extend([
        "",
        "## Role Contract",
        "",
        "- Backend owns business rules, validation, state transitions, rewards, permissions, and final calculation results.",
        "- Flutter owns pure UI rendering, input collection, navigation, loading/error/empty states, and displaying backend results.",
        "- QA validates every AC ID against the same derived contract and records evidence by PRD anchor.",
        "",
    ])
    return "\n".join(lines)


def build_change_report(previous: dict, manifest: dict) -> str:
    old = {item.get("anchor"): item for item in (previous.get("features") or [])} if previous else {}
    new = {item.get("anchor"): item for item in manifest["features"]}
    added = sorted(set(new) - set(old))
    removed = sorted(set(old) - set(new))
    changed = sorted(anchor for anchor in set(new) & set(old) if new[anchor].get("hash") != old[anchor].get("hash"))
    unchanged = sorted(anchor for anchor in set(new) & set(old) if new[anchor].get("hash") == old[anchor].get("hash"))

    return "\n".join([
        GENERATED_HEADER,
        "# PRD Sync Change Report",
        "",
        f"Generated at: `{manifest['generated_at']}`",
        f"Source hash: `{manifest['source']['hash']}`",
        "",
        "## Summary",
        "",
        f"- Added anchors: {len(added)}",
        f"- Changed anchors: {len(changed)}",
        f"- Removed anchors: {len(removed)}",
        f"- Unchanged anchors: {len(unchanged)}",
        "",
        "## Added",
        *(f"- {item}" for item in added),
        "",
        "## Changed",
        *(f"- {item}" for item in changed),
        "",
        "## Removed",
        *(f"- {item}" for item in removed),
        "",
    ])


def read_previous_manifest(path: Path) -> dict:
    if not path.exists():
        return {}
    try:
        return yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    except Exception:
        return {}


def sync(prd_path: Path, out_dir: Path, strict: bool = False) -> dict:
    validation = prd_validate.validate(prd_path, strict=strict)
    if not validation["ok"]:
        return {"ok": False, "validation": validation, "writes": []}

    prd_text = prd_path.read_text(encoding="utf-8")
    meta = prd_validate._metadata(prd_text)
    features = collect_features(prd_text)
    manifest = build_manifest(prd_path, prd_text, meta, features)

    manifest_path = out_dir / "prd-manifest.yml"
    previous = read_previous_manifest(manifest_path)
    task_map = build_task_map(manifest)
    acceptance_spec = build_acceptance_spec(manifest)
    change_report = build_change_report(previous, manifest)

    out_dir.mkdir(parents=True, exist_ok=True)
    writes = [
        (manifest_path, yaml.safe_dump(manifest, allow_unicode=True, sort_keys=False)),
        (out_dir / "task-map.yml", yaml.safe_dump(task_map, allow_unicode=True, sort_keys=False)),
        (out_dir / "acceptance-spec.md", acceptance_spec),
        (out_dir / "change-report.md", change_report),
    ]
    for path, content in writes:
        path.write_text(content, encoding="utf-8")

    return {
        "ok": True,
        "validation": validation,
        "feature_count": len(features),
        "source_hash": manifest["source"]["hash"],
        "writes": [str(path) for path, _ in writes],
    }


def main() -> None:
    root = Path(__file__).resolve().parent.parent
    parser = argparse.ArgumentParser(description="Sync PRD.md into agent-facing derived artifacts")
    parser.add_argument("--prd", default=str(root / "docs" / "PRD.md"), help="path to PRD.md")
    parser.add_argument("--out", default=str(root / "docs" / "agent"), help="output directory")
    parser.add_argument("--strict", action="store_true", help="treat unresolved placeholders as blockers")
    parser.add_argument("--json", action="store_true", help="emit JSON")
    args = parser.parse_args()

    result = sync(Path(args.prd).resolve(), Path(args.out).resolve(), strict=args.strict)
    if args.json:
        print(json.dumps(result, ensure_ascii=False, indent=2))
    else:
        print("=== DeliverHQ PRD Sync ===")
        if result["ok"]:
            print(f"features: {result['feature_count']}")
            for item in result["writes"]:
                print(f"wrote: {item}")
            print("PASS")
        else:
            print("BLOCKED")
            for item in result["validation"].get("blockers", []):
                print(f"- {item}")
    sys.exit(0 if result["ok"] else 1)


if __name__ == "__main__":
    main()
